# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"1\n\x0b\x43hatMessage\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\"\n\rClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"2\n\x0bMessageList\x12#\n\x08messages\x18\x01 \x03(\x0b\x32\x11.chat.ChatMessage2s\n\x0b\x43hatService\x12-\n\x0bSendMessage\x12\x11.chat.ChatMessage\x1a\x0b.chat.Empty\x12\x35\n\x0bGetMessages\x12\x13.chat.ClientRequest\x1a\x11.chat.MessageListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=69
  _globals['_EMPTY']._serialized_start=71
  _globals['_EMPTY']._serialized_end=78
  _globals['_CLIENTREQUEST']._serialized_start=80
  _globals['_CLIENTREQUEST']._serialized_end=114
  _globals['_MESSAGELIST']._serialized_start=116
  _globals['_MESSAGELIST']._serialized_end=166
  _globals['_CHATSERVICE']._serialized_start=168
  _globals['_CHATSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
